services:
  sni5gect:
    image: sni5gect
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CORES: ${BUILD_CORES:-0}
    container_name: sni5gect
    privileged: true
    restart: unless-stopped
    # entrypoint: /sbin/init # Causes issues with host, making it restart
    entrypoint: ["sleep", "infinity"]
    network_mode: host
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - type: bind
        source: "./configs/sniffer"
        target: /root/sni5gect/configs
        read_only: true
